name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-push:
    runs-on: ubuntu-latest
    environment: Assessemnt
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
      - name: Build and Push
        run: cd /app |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/back-end:latest ./back-end
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/front-end:latest ./front-end/app
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/back-end:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/front-end:latest
          

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    environment: Assessemnt
    steps:
      - name: Remote SSH Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: 
            docker compose pull
            docker compose up -d
